Models/VehicleAssignment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace RowVehiclePoolMVC.Models
{
    public partial class VehicleAssignment
    {
        [Key]
        public int VehReqNo { get; set; }
        [Key]
        [Column(TypeName = "decimal(5, 0)")]
        public decimal AssignNo { get; set; }
        [Required]
        [StringLength(5)]
        public string AssignTagNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AssignDepartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AssignReturnDate { get; set; }
        [Required]
        [StringLength(50)]
        public string Comments { get; set; }
    }
}

Models/VehicleRequisition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace RowVehiclePoolMVC.Models
{
    public partial class VehicleRequisition
    {
        [Key]
        [Column(TypeName = "ID")]
        [Display(Name = "Request Number")]
        public int VehReqNo { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name ="Date Requested")]
        public DateTime VehReqDate { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Requestor")]
        public string Requestor { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Veh Type")]
        public string VehType { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Destination")]
        public string Destination { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Duties")]
        public string Duties { get; set; }
        [Column(TypeName = "decimal(2, 0)")]
        [DisplayFormat(DataFormatString = "{0:n0}")]
        [Display(Name = "Number in Party")]
        public decimal NoInParty { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Division")]
        public string ReqDivision { get; set; }
        [Required]
        [Column("ReqSectionID")]
        [StringLength(4)]
        [Display(Name = "Section")]
        public string ReqSectionId { get; set; }
        [Required]
        [StringLength(3)]
        [Display(Name ="Budget")]
        public string ReqBudget { get; set; }
        [Required]
        [StringLength(4)]
        [Display(Name = "Function")]
        public string ReqFunction { get; set; }
        [Required]
        [StringLength(6)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage ="Characters not allowed")]
        [Display(Name = "Job No")]
        public string ReqJobNo { get; set; }
        [Required]
        [Column("ReqFAP")]
        [StringLength(11)]
        [Display(Name = "FAP")]
        public string ReqFap { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Comments")]
        public string ReqComments { get; set; }
        [Column(TypeName = "datetime")]
        [Required]
        [Display(Name = "Depart Date")]
        public DateTime ReqDepartDate { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name = "Return Date")]
        public DateTime ReqReturnDate { get; set; }
        [Required]
        [StringLength(8)]
        [Display(Name = "User ID")]
        public string Userid { get; set; }
        [Required]
        [Display(Name ="Status")]
        [StringLength(1)]
        public string VehReqStatus { get; set; }
        [StringLength(50)]
        [Display(Name = "Division Head")]
        public string NotificationDivHead { get; set; }
        [StringLength(50)]
        [Display(Name="Manager")]
        public string NotificationMan { get; set; }
        [StringLength(50)]
        [Display(Name ="Email Address")]
        public string EmailAddress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastChangeDate { get; set; }
        [StringLength(7)]
        public string LastChangeUserid { get; set; }
    }
}

ViewModels/AssignmentDetail.cs
using System;

namespace RowVehiclePoolMVC.ViewModels
{
    public class AssignmentDetail
    {
        public int VehReqNo { get; set; }
        public string Duties { get; set; }
        public DateTime VehReqDate { get; set; }
        public string Requestor { get; set; }
        public string VehType { get; set; }
        public string Destination { get; set; }
        public DateTime ReqDepartDate { get; set; }
        public DateTime ReqReturnDate { get; set; }
        public string ReqDivision { get; set; }
        public string ReqBudget { get; set; }
        public string AssignTagNo { get; set; }
        public string VehReqStatus { get; set; }
        public int NoInParty { get; set; }
        public string ReqComments { get; set; }
        public string JobNumber { get; set; }
        public string Function { get; set; }
        public string FAP { get; set; }
    }
}

Controllers/VehicleAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RowVehiclePoolMVC.Context;
using RowVehiclePoolMVC.Models;
using RowVehiclePoolMVC.ViewModels;
using RowVehiclePoolMVC.Utilities;
using Org.BouncyCastle.Asn1.Ocsp;
using RowVehiclePoolMVC.Services;

namespace RowVehiclePoolMVC.Controllers
{
    public class VehicleAssignmentsController : Controller
    {
        private readonly RvpAppContext _context;
        private readonly IMailService _mailService;

        public VehicleAssignmentsController(RvpAppContext context, IMailService mailService)
        {
            _context = context;
            _mailService = mailService;
        }

        // GET: VehicleAssignments
        public async Task<IActionResult> Index()
        {
            return View(await _context.VehicleAssignment.ToListAsync());
        }

        // GET: VehicleAssignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleAssignment = await _context.VehicleAssignment
                .FirstOrDefaultAsync(m => m.VehReqNo == id);
            if (vehicleAssignment == null)
            {
                return NotFound();
            }

            return View(vehicleAssignment);
        }

        // GET: VehicleAssignments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleAssignments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VehReqNo,AssignNo,AssignTagNo,AssignDepartDate,AssignReturnDate,Comments")] VehicleAssignment vehicleAssignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicleAssignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleAssignment);
        }

        [HttpGet]
        public IActionResult VehicleAssigned(int id) 
        {
            var vehicleRequisition = _context.VehicleRequisition.Where(c => c.VehReqNo == id).FirstOrDefault();
            return View(vehicleRequisition); 
        }

        [HttpGet]
        public async Task<IActionResult> AssignVehicle(string tagNumber, int vehReqNo)
        {
            try
            {
                var vehRequisition = await _context.VehicleRequisition.Where(c => c.VehReqNo == vehReqNo).FirstOrDefaultAsync();
                if (vehRequisition == null)
                {
                    return BadRequest();
                }
                var vehicle = await _context.Vehicle.Where(c => c.TagNumber == tagNumber).FirstOrDefaultAsync(); 
                if(vehicle == null)
                {
                    return BadRequest();
                }
                var vM = new AssignVehicleVM()
                {
                    TagNumber  = tagNumber,
                    Comments    = vehRequisition.ReqComments,
                    DepartDate = vehRequisition.ReqDepartDate,
                    ReturnDate = vehRequisition.ReqReturnDate,
                    DepartTime = vehRequisition.ReqDepartDate.ToString("HH:MM:SS"),
                    ReturnTime = vehRequisition.ReqReturnDate.ToString("HH:mm:ss"),
                    VehReqNo   = vehReqNo,
                };
                vM.VehicleWeek = Utility.GetVehicleWeek(_context, vM.DepartDate.Date.ToString("yyyyMMdd"));
                ViewBag.TimeOfDayVals = new List<SelectListItem>()
                {
                     new SelectListItem(){Text="Early",   Value="07:29:00"}
                    ,new SelectListItem(){Text="7:30 AM", Value="07:30:00"}
                    ,new SelectListItem(){Text="8:00 AM", Value="08:00:00"}
                    ,new SelectListItem(){Text="8:30 AM", Value="08:30:00"}
                    ,new SelectListItem(){Text="9:00 AM", Value="09:00:00"}
                    ,new SelectListItem(){Text="9:30 AM", Value="09:30:00"}
                    ,new SelectListItem(){Text="10:00 AM",Value="10:00:00"}
                    ,new SelectListItem(){Text="10:30 AM",Value="10:30:00"}
                    ,new SelectListItem(){Text="11:00 AM",Value="11:00:00"}
                    ,new SelectListItem(){Text="11:30 AM",Value="11:30:00"}
                    ,new SelectListItem(){Text="12:00 PM",Value="12:00:00"}
                    ,new SelectListItem(){Text="12:30 PM",Value="12:30:00"}
                    ,new SelectListItem(){Text="1:00 PM",Value="13:00:00"}
                    ,new SelectListItem(){Text="1:30 PM",Value="13:30:00"}
                    ,new SelectListItem(){Text="2:00 PM",Value="14:00:00"}
                    ,new SelectListItem(){Text="2:30 PM",Value="14:30:00"}
                    ,new SelectListItem(){Text="3:00 PM",Value="15:00:00"}
                    ,new SelectListItem(){Text="3:30 PM",Value="15:30:00"}
                    ,new SelectListItem(){Text="4:00 PM",Value="16:00:00"}
                    ,new SelectListItem(){Text="4:30 PM",Value="16:30:00"}
                    ,new SelectListItem(){Text="Late",Value="16:31:00"}
                };
                return View(vM);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);

            }
            return View("VehicleAssign");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignVehicle(AssignVehicleVM vehicleAssignment)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    VehicleRequisition vehicleRequisition = _context.VehicleRequisition.Where(c => c.VehReqNo == vehicleAssignment.VehReqNo).FirstOrDefault();
                    vehicleRequisition.ReqReturnDate = vehicleAssignment.ReturnDate;
                    vehicleRequisition.ReqDepartDate = vehicleAssignment.DepartDate;
                    vehicleRequisition.ReqComments = vehicleAssignment.Comments;
                    vehicleRequisition.VehReqStatus = "A";
                    var newAssignmentNo = _context.VehicleAssignment.Max(c => c.AssignNo) + 1;
                    _context.Update(vehicleRequisition);

                    var assignment = _context.VehicleAssignment.Where(c => c.VehReqNo.Equals(vehicleAssignment.VehReqNo)).FirstOrDefault();
                    if (assignment == null)
                    {
                        await _context.VehicleAssignment.AddAsync(new VehicleAssignment()
                        {
                            AssignNo = newAssignmentNo,
                            AssignDepartDate = vehicleAssignment.DepartDate,
                            AssignTagNo = vehicleAssignment.TagNumber,
                            AssignReturnDate = vehicleAssignment.ReturnDate,
                            Comments = vehicleAssignment.Comments,
                            VehReqNo = vehicleAssignment.VehReqNo
                        });
                    }
                    else
                    {
                        assignment.AssignReturnDate = vehicleAssignment.ReturnDate;
                        assignment.AssignDepartDate= vehicleAssignment.DepartDate;
                        assignment.Comments= vehicleAssignment.Comments;   
                        assignment.AssignTagNo= vehicleAssignment.TagNumber;
                        _context.Update(assignment);
                    }
                    await _context.SaveChangesAsync();

                    var requisitionVM = new VehicleRequisitionVM()
                    {
                        Destination = vehicleRequisition.Destination,
                        AssignedTagNo = vehicleAssignment.TagNumber,
                        Duties = vehicleRequisition.Duties,
                        EmailAddress = vehicleRequisition.EmailAddress,
                        NoInParty = vehicleRequisition.NoInParty,
                        ReqBudget = vehicleRequisition.ReqBudget,
                        ReqComments = vehicleAssignment.Comments,
                        ReqDepartDate = vehicleAssignment.DepartDate,
                        ReqReturnDate = vehicleAssignment.ReturnDate,
                        ReqSectionId = vehicleRequisition.ReqSectionId,
                        ReqDivision = vehicleRequisition.ReqDivision,
                        NotificationDivHead = vehicleRequisition.NotificationDivHead,
                        ReqFap = vehicleRequisition.ReqFap,
                        ReqFunction = vehicleRequisition.ReqFunction,
                        ReqJobNo = vehicleRequisition.ReqJobNo,
                        VehType = vehicleRequisition.VehType,
                        VehReqDate = vehicleAssignment.ReturnDate,
                        Userid = vehicleRequisition.Userid,
                        VehReqNo = vehicleAssignment.VehReqNo,
                        NotificationMan = vehicleRequisition.NotificationMan,
                        Requestor = vehicleRequisition.Requestor,
                    };
                    SendAssignmentEmails(_context, requisitionVM);
                    return View("VehicleAssigned",requisitionVM);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error in AssignVehicle - " + ex.Message);
            }
            return View(vehicleAssignment);
        }

        private async void SendAssignmentEmails(RvpAppContext context, VehicleRequisitionVM vehicleRequisition)
        {

            var mailRequest = new MailRequest()
            {

Views/VehicleRequisitions/AssignmentDetail.cshtml
@model RowVehiclePoolMVC.ViewModels.AssignmentDetailVM

@{
    ViewData["Title"] = "AssignmentDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AssignmentDetail</h1>

<div class="container-fluid">
    <div class="row row-height">
        <div class="col col-5 left">
            <h4>VehicleRequisition</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.VehReqDate)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.VehReqDate)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.Requestor)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.Requestor)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.VehType)
                    <select asp-for="@Model.VehicleRequisition.VehType" asp-items="ViewBag.VehicleTypes">
                    </select>
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.VehType, new{ @id = "VehType", @value=Model.VehicleRequisition.VehType})
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.Destination)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.Destination)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.Duties)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.Duties)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.NoInParty)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.NoInParty)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqDivision)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqDivision)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqSectionId)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqSectionId)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqBudget)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqBudget)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqFunction)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqFunction)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqJobNo)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqJobNo)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqFap)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqFap)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqComments)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqComments)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqDepartDate)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqDepartDate)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.ReqReturnDate)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.ReqReturnDate)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.Userid)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.Userid)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.VehReqStatus)
                    <select asp-for="@Model.VehicleRequisition.VehReqStatus" asp-items="ViewBag.RequisitionStatuses"></select>
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.VehReqStatus)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.NotificationDivHead)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.NotificationDivHead)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.NotificationMan)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.NotificationMan)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.VehicleRequisition.EmailAddress)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.VehicleRequisition.EmailAddress)
                </dd>
            </dl>
            <input type="hidden" asp-for="@Model.VehicleRequisition.ReqDepartDate" />
            <input type="hidden" asp-for="@Model.VehicleRequisition.ReqReturnDate" />
            <input type="hidden" asp-for="@Model.VehicleRequisition.VehReqNo" />
            <div>
                @if(Model.VehicleRequisition.VehReqStatus == "A")
                {
                    <a asp-action="Edit" asp-controller="VehicleAssignments" asp-route-id="@Model.VehicleRequisition.VehReqNo" >Edit</a>
                }
                else if(Model.VehicleRequisition.VehReqStatus == "P")
                {
                    <input id="search" type="submit" value="submit">
                }
                @*<a asp-action="Index">Back to List</a>*@
            </div>
        </div>
        <div class="col col-7 right" id="_weekly">
            <partial name="_weekly" model="@Model.VehicleWeek"/>
        </div>
    </div>
    <div class="row" width="100%">
        <div class="col col-12 center" id="AvailableVehicles">
        </div>
    </div>
    <div class="row" width="100%">
        <div class="col col-12">
            <p align="center"><a type="button" asp-action="VehicleAssign" >Back</a><br><a asp-action="Index" asp-controller="Home">Back to the Main Menu</a></p>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        var url = '@Url.Action("ShowAvailableVehiclesByType", "Vehicle")';
        $('#search').click(function(){
            var vehicleType = $("#VehicleRequisition_VehType").val();
            var departDate = $("#VehicleRequisition_ReqDepartDate").val();
            var returnDate = $("#VehicleRequisition_ReqReturnDate").val();
            var vehReqNo = $("#VehicleRequisition_VehReqNo").val();
            $('#AvailableVehicles').load(url, {vehType: vehicleType, departDate: departDate, returnDate: returnDate, vehReqNo: vehReqNo});
        });

        Date.prototype.addDays = function (days) {
            var date = new Date(this.valueOf());
            date.setDate(date.getDate() + days);
            return date;
        }

        var DisplayWeekly = function (days) {
            var newDate = new Date($("#usageDate").val());
            newDate = newDate.addDays(days);
            var sDate = (newDate.getMonth() + 1) + '/' + newDate.getDate() + '/' + newDate.getFullYear();
            $.ajax({
                url: '@Url.Action("WeeklyPartial","Vehicle")?sDate=' + sDate,
                type: "GET",
                async: true,
            })
                .done(function (partialViewResult) {
                    $("#_weekly").html(partialViewResult);
                })
        }

    </script>
}

Views/VehicleRequisitions/Delete.cshtml
@model RowVehiclePoolMVC.ViewModels.VehicleRequestVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehicleRequisition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehReqDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehReqDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehRequestor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehRequestor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duties)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duties)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoInParty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoInParty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqDivision)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqDivision)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqSectionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqSectionId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqBudget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqBudget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqFunction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqFunction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqJobNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqJobNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqFap)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqFap)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqComments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqComments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqDepartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqDepartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReqReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReqReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehReqStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehReqStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NotificationDivHead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NotificationDivHead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NotificationMan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NotificationMan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastChangeUserid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastChangeUserid)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VehReqNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ViewAllRequisitions">Back to List</a>
    </form>
</div>